"""Build the standalone Windows executable.

Nothing here is tied to one developer's machine: the Choice SDK is located by
importing it from the active environment, so the build works anywhere the
dependencies are installed:

    pip install ./kkunal-1.2.0.tar.gz
    pip install -r backend/requirements.txt -r engine/requirements.txt \
                -r client-desktop/requirements.txt
    python client-desktop/build_exe.py
"""

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path

DESKTOP_DIR = Path(__file__).resolve().parent
REPO_ROOT = DESKTOP_DIR.parent
APP_NAME = "ChoiceFinxTrader"


def locate_choice_sdk() -> Path:
    """Find the installed choice_api package.

    CHOICE_API_PATH overrides, for a source checkout that is not installed.
    """
    override = os.environ.get("CHOICE_API_PATH")
    if override:
        path = Path(override).expanduser().resolve()
        candidate = path / "choice_api" if path.name != "choice_api" else path
        if candidate.is_dir():
            return candidate
        raise SystemExit(f"CHOICE_API_PATH does not contain choice_api: {path}")

    spec = importlib.util.find_spec("choice_api")
    if spec and spec.submodule_search_locations:
        return Path(list(spec.submodule_search_locations)[0])

    raise SystemExit(
        "choice_api is not installed. Run:\n"
        f"    pip install {REPO_ROOT / 'kkunal-1.2.0.tar.gz'}\n"
        "or set CHOICE_API_PATH to a source checkout."
    )


def write_version_file(target: Path, version: str) -> Path:
    """Windows version resource, so the binary is identifiable in Explorer."""
    parts = (version.split(".") + ["0", "0", "0", "0"])[:4]
    numeric = ", ".join(parts)
    target.write_text(
        f"""VSVersionInfo(
  ffi=FixedFileInfo(filevers=({numeric}), prodvers=({numeric}),
                    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Choice FINX Algo Platform'),
      StringStruct('FileDescription', 'Choice FINX Algo Trading Platform'),
      StringStruct('FileVersion', '{version}'),
      StringStruct('InternalName', '{APP_NAME}'),
      StringStruct('OriginalFilename', '{APP_NAME}.exe'),
      StringStruct('ProductName', 'Choice FINX Algo Trading Platform'),
      StringStruct('ProductVersion', '{version}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""",
        encoding="utf-8",
    )
    return target


def sync_ui() -> Path:
    """Copy the single UI source into the bundle staging directory.

    ``frontend-user/`` is the only place the interface is edited; the copy
    under ``client-desktop/static`` is a build artefact, refreshed here so the
    shipped binary can never lag behind the source.
    """
    source = REPO_ROOT / "frontend-user"
    target = DESKTOP_DIR / "static"
    if not (source / "index.html").is_file():
        raise SystemExit(f"UI source not found: {source / 'index.html'}")

    if target.exists():
        shutil.rmtree(target)
    # Only what the app serves. `frontend-user/` also holds verify_ui.py, which
    # was being copied into the bundle and shipped inside the executable — test
    # tooling has no business in a product binary.
    shutil.copytree(source, target,
                    ignore=shutil.ignore_patterns("*.py", "__pycache__", "*.md"))

    # The admin page is deliberately NOT bundled. On a user's machine it reads
    # their own local database, so it shows them nothing about anyone else and
    # hands them a control surface for no reason. It belongs to a server
    # deployment, where the database is central and the operator owns the host.
    # Build with CHOICE_BUNDLE_ADMIN=1 for such a build.
    if os.environ.get("CHOICE_BUNDLE_ADMIN") == "1":
        admin = REPO_ROOT / "frontend-admin" / "index.html"
        if admin.is_file():
            shutil.copy(admin, target / "admin.html")
            print(f"Admin staged: {admin} -> {target / 'admin.html'}")

    print(f"UI staged: {source} -> {target}")
    return target


def write_build_config(licence_server: str) -> None:
    """Bake the licence server URL into the build, or clear it.

    Rewritten every time rather than only when a URL is given. A leftover
    file would silently license a build meant to be unlicensed, or point a
    new release at a server that has been retired, and neither is visible by
    looking at the binary.
    """
    target = DESKTOP_DIR / "app" / "_build.py"
    url = (licence_server or "").strip().rstrip("/")
    lines = [
        '"""Generated by build_exe.py. Do not edit."""',
        "",
        f"LICENCE_SERVER_URL = {url!r}",
        "",
    ]
    target.write_text('\n'.join(lines), encoding="utf-8")
    if url:
        print(f"Licence server baked in: {url}")
    else:
        print("Licence server: none - this build cannot be revoked once shared.")


def check_target_writable(one_file: bool) -> None:
    """Fail early and clearly if the previous binary is still running.

    Windows locks a running executable, and PyInstaller only discovers this at
    the very end of a multi-minute build, reporting a bare PermissionError.
    """
    target = DESKTOP_DIR / "dist" / (
        f"{APP_NAME}.exe" if one_file else f"{APP_NAME}/{APP_NAME}.exe"
    )
    if not target.exists():
        return

    # Probe with an actual write handle. Renaming is *not* a valid test:
    # Windows permits renaming a running executable and only blocks writing to
    # and deleting it, so a rename probe passes and PyInstaller still dies on
    # os.remove at the end of the build.
    try:
        with open(target, "r+b"):
            pass
    except (OSError, PermissionError):
        raise SystemExit(
            f"Cannot overwrite {target}\n\n"
            f"{APP_NAME} is still running and Windows has the file locked.\n"
            "Close the application (and any browser tab it opened), then retry:\n"
            f"    taskkill /F /IM {APP_NAME}.exe /T"
        )

    # Clear the old binary now rather than leaving PyInstaller to delete it at
    # the very end. Antivirus routinely takes a transient read lock on a
    # freshly written executable, and when it does so during the build the
    # final os.remove fails with a bare PermissionError after several minutes
    # of work. Removing it up front means there is nothing left to lock.
    #
    # Keep a copy until the build succeeds: a failed build should not leave the
    # user with no working executable at all.
    backup = target.with_suffix(target.suffix + ".previous")
    try:
        backup.unlink(missing_ok=True)
        target.rename(backup)
    except (OSError, PermissionError) as exc:
        print(f"Note: could not set the previous binary aside ({exc}); "
              "PyInstaller will overwrite it in place.")


def build(one_file: bool, windowed: bool, version: str,
          licence_server: str = "") -> int:
    sdk_dir = locate_choice_sdk()
    write_build_config(licence_server)
    check_target_writable(one_file)
    sync_ui()
    separator = ";" if sys.platform == "win32" else ":"

    def data(source: Path, dest: str) -> str:
        return f"{source}{separator}{dest}"

    version_file = write_version_file(DESKTOP_DIR / "version_info.txt", version)

    command = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm", "--clean",
        "--onefile" if one_file else "--onedir",
        "--name", APP_NAME,
        "--distpath", str(DESKTOP_DIR / "dist"),
        "--workpath", str(DESKTOP_DIR / "build"),
        "--specpath", str(DESKTOP_DIR),
        # UPX compression on an unsigned binary is a frequent antivirus
        # false-positive trigger, and saves little on a bundle this size.
        "--noupx",
        "--paths", str(sdk_dir.parent),
        "--add-data", data(DESKTOP_DIR / "static", "static"),
        "--add-data", data(REPO_ROOT / "backend", "backend"),
        "--add-data", data(REPO_ROOT / "engine", "engine"),
        "--add-data", data(sdk_dir, "choice_api"),
    ]

    if sys.platform == "win32":
        command += ["--version-file", str(version_file)]
    if windowed:
        command.append("--windowed")

    for module in [
        "choice_api", "uvicorn", "fastapi", "fastapi.middleware.cors", "httpx",
        "pandas", "numpy", "bcrypt", "sqlalchemy", "email_validator", "pydantic",
        "pydantic_settings", "jose", "jose.jwt", "cryptography",
        # Generated by write_build_config(). Imported inside a try/except,
        # which the analysis can miss — and a licensed build shipping as
        # unlicensed looks fine and cannot be revoked.
        "app._build",
        # Fernet encrypts the persisted broker session. PyInstaller does not
        # find it from the import alone, and a missing module here does not
        # surface until a user connects — name it explicitly.
        "cryptography.fernet",
        "cryptography.hazmat.primitives.ciphers", "websockets", "websocket",
        # Frozen urllib HTTPS to GitHub needs the CA bundle; without it the
        # updater GET fails and Health used to claim "Up to date".
        "certifi",
    ]:
        command += ["--hidden-import", module]

    for package in [
        "choice_api", "fastapi", "pydantic", "sqlalchemy", "uvicorn", "requests",
        "jose", "cryptography", "certifi",
    ]:
        command += ["--collect-submodules", package]

    command.append(str(DESKTOP_DIR / "app" / "cli.py"))

    print(f"Choice SDK: {sdk_dir}")
    print(f"Building {APP_NAME} ({'one-file' if one_file else 'one-folder'}) ...")
    result = subprocess.run(command, cwd=DESKTOP_DIR)

    target = DESKTOP_DIR / "dist" / (
        f"{APP_NAME}.exe" if one_file else f"{APP_NAME}/{APP_NAME}.exe"
    )
    backup = target.with_suffix(target.suffix + ".previous")

    if result.returncode == 0:
        # The new binary is good, so the copy set aside earlier can go.
        try:
            backup.unlink(missing_ok=True)
        except OSError:
            pass
        print(f"\nBuilt: {target}")

        # A .env beside the executable is read ahead of the per-user one, so
        # sending the whole dist folder hands every client this machine's
        # SECRET_KEY and its Choice environment. The .exe alone is correct: it
        # generates its own key on first run.
        stray = target.parent / ".env"
        if stray.is_file():
            print(
                f"\nWARNING: {stray}\n"
                "         sits beside the executable and would be read by any copy of\n"
                "         this folder. It contains this machine's SECRET_KEY.\n"
                "         Send the .exe by itself, not the folder."
            )
        print(
            "\nBefore distributing, sign the executable with a code-signing\n"
            "certificate. An unsigned binary triggers a SmartScreen warning on\n"
            "every download:\n"
            f'    signtool sign /fd SHA256 /tr <timestamp-url> /td SHA256 "{target}"'
        )
    else:
        print(f"Build failed with exit code {result.returncode}")
        if backup.exists() and not target.exists():
            print(
                f"\nThe previous working binary is still here:\n    {backup}\n"
                f"Rename it back to {target.name} if you need it while you "
                "sort the build out."
            )
    return result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the desktop executable.")
    parser.add_argument(
        "--onedir", action="store_true",
        help="Build a folder instead of a single file. Starts much faster, "
             "because one-file re-extracts the whole bundle on every launch.",
    )
    parser.add_argument(
        "--windowed", action="store_true",
        help="Hide the console window. Startup errors become invisible, so "
             "keep the console while testing.",
    )
    parser.add_argument("--app-version", default="1.2.10")
    parser.add_argument(
        "--licence-server", default="",
        help="Licence service URL to bake into this build, e.g. "
             "https://licences.example.com. Omit for an unlicensed build, "
             "which cannot be revoked once handed out.",
    )
    args = parser.parse_args()
    return build(
        one_file=not args.onedir, windowed=args.windowed, version=args.app_version,
        licence_server=args.licence_server,
    )


if __name__ == "__main__":
    raise SystemExit(main())
